# გააკეთეთ 30 მაგალითი შედარებით ოპერატორებზე. 

a = int(input("enter a number"))
b = int(input("enter a number"))
c = int(input("enter a number"))
d = int(input("enter a number"))
e = int(input("enter a number"))
f = int(input("enter a number"))
g = int(input("enter a number"))
h = int(input("enter a number"))
i = int(input("enter a number"))
j = int(input("enter a number"))
k = int(input("enter a number"))
l = int(input("enter a number"))
m = int(input("enter a number"))
n = int(input("enter a number"))
o = int(input("enter a number"))
p = int(input("enter a number"))
q = int(input("enter a number"))
r = int(input("enter a number"))
s = int(input("enter a number"))
t = int(input("enter a number"))
u = int(input("enter a number"))
v = int(input("enter a number"))
w = int(input("enter a number"))
x = int(input("enter a number"))
y = int(input("enter a number"))
z = int(input("enter a number"))
a1 = int(input("enter a number"))
b1 = int(input("enter a number"))
c1 = int(input("enter a number"))
d1 = int(input("enter a number"))
print(a>b)
print(b<a)
print(b>c)
print(c<b)
print(c>d)
print(g>h)
print(f>o)
print(p>w)
print(q<d)
print(p<a)
print(l<k)
print(y>p)
print(c<t)
print(x>z)
print(z>g)
print(l>a)
print(s>v)
print(w>v)
print(c1>a1)
print(b1>d1)
print(d1>p)
print(c1>q)
print(a1>l)
print(v<o)
print(m>x)
print(z>q)
print(z>l)
print(l>e)
print(d1>k)
print(c1>j)



